### ISSUE TITLE
Information update for the paper 57. "MISSRec: Pre-training and Transferring Multi-modal Interest-aware Sequence Representation for Recommendation"

### ISSUE THREAD

**Issue by gimpong** [KingGugu/DA-CL-4Rec#4]
Hi KingGugu,

Thanks for your awesome repository! It will help many researchers gain insights into the latest DA techniques and benefit the RS community. 

I am happy to announce the code release of our paper, "MISSRec: Pre-training and Transferring Multi-modal Interest-aware Sequence Representation for Recommendation", at https://github.com/gimpong/MM23-MISSRec. 

Thank you for considering our latest paper in this repository, and I would appreciate it if you attached the code link to the paper record. 

Kind regards, 
Jinpeng

**Comment by KingGugu** [comment]
Thanks for your attention to this repository😆.

I have attached the code link to the corresponding paper.

Have a good day!
