### ISSUE TITLE
Kindly request the addition of an SSL Recommendation Framework.

### ISSUE THREAD

**Issue by Re-bin** [KingGugu/DA-CL-4Rec#5]
Hi KingGugu,

Thanks for your awesome repository!

Our current paper in WSDM'24, "SSLRec: A Self-Supervised Learning Framework for Recommendation", proposes a self-supervised learning framework for recommendation.

I would appreciate it if you consider attaching this paper the code link to your awesome reposity!

paper link: https://arxiv.org/abs/2308.05697
code link: https://github.com/HKUDS/SSLRec

Best regards,
Xubin

**Comment by KingGugu** [comment]
Thanks for your attention to this repository😆.

I have been following SSLRec for a long time and it is a very comprehensive and easy-to-use framework. I have attached your paper and the code link.

Have a good day!

**Comment by Re-bin** [comment]
Thanks!
